import { db, auth } from "../../shared/js/firebase-app.js";
import { allowedAdmins } from "../../shared/js/firebase-config.js";
import { GoogleAuthProvider, signInWithPopup, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { collection, addDoc, updateDoc, deleteDoc, doc, query, orderBy, onSnapshot, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
const $=id=>document.getElementById(id), provider=new GoogleAuthProvider();let announcements=[],adminKeyword="";
$("loginBtn").onclick=async()=>{try{$("loginBtn").disabled=true;$("loginBtn").textContent="登入中...";await signInWithPopup(auth,provider)}catch(e){console.error(e);alert("Google 登入失敗：\n"+(e.message||e.code))}finally{$("loginBtn").disabled=false;$("loginBtn").textContent="使用 Google 登入"}};
$("logoutBtn").onclick=()=>signOut(auth);
onAuthStateChanged(auth,u=>{if(!u){$("loginView").classList.remove("hidden");$("appView").classList.add("hidden");return}if(!allowedAdmins.includes(u.email)){alert("這個帳號沒有後台權限："+u.email);signOut(auth);return}$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");$("userInfo").textContent=u.email;resetForm();listenPosts()});
let unsub=null;function listenPosts(){if(unsub)return;unsub=onSnapshot(query(collection(db,"announcements"),orderBy("date","desc")),s=>{announcements=s.docs.map(d=>({id:d.id,...d.data()}));updateStats();renderList();renderRecent();renderLibrary()},e=>{console.error(e);alert("讀取公告失敗：\n"+e.message)})}
document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>showView(b.dataset.view));function showView(v){document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===v));document.querySelectorAll(".view").forEach(x=>x.classList.add("hidden"));$("view-"+v).classList.remove("hidden");$("pageTitle").textContent={dashboard:"儀表板",posts:"公告管理",library:"附件中心",settings:"系統設定"}[v]||"管理平台"}
$("resetBtn").onclick=resetForm;$("adminSearch").oninput=e=>{adminKeyword=e.target.value.trim();renderList()};
function updateStats(){$("statTotal").textContent=announcements.length;$("statPublished").textContent=announcements.filter(a=>a.published!==false).length;$("statDraft").textContent=announcements.filter(a=>a.published===false).length;$("statFiles").textContent=announcements.reduce((s,a)=>s+(a.files?.length||0),0)}
$("postForm").onsubmit=async e=>{e.preventDefault();const title=$("title").value.trim(),content=$("content").value.trim(),date=$("date").value;if(!title||!content||!date){alert("標題、日期、內容必填");return}const images=$("images").value.split("\n").map(x=>x.trim()).filter(Boolean).map(url=>({url,name:url.split("/").pop()}));const files=$("files").value.split("\n").map(x=>x.trim()).filter(Boolean).map(line=>{const [name,url]=line.split("|").map(x=>x.trim());return{name:name||url,url:url||name}});const data={title,content,date,category:$("category").value,published:$("published").checked,pinned:$("pinned").checked,images,files,updatedAt:serverTimestamp()};try{const id=$("editId").value;if(id)await updateDoc(doc(db,"announcements",id),data);else{data.createdAt=serverTimestamp();await addDoc(collection(db,"announcements"),data)}alert("已儲存");resetForm()}catch(e){console.error(e);alert("儲存失敗：\n"+e.message)}};
function renderList(){let data=announcements.filter(a=>!adminKeyword||(a.title||"").includes(adminKeyword)||(a.content||"").includes(adminKeyword));$("postList").innerHTML=data.length?data.map(cardHtml).join(""):'<div class="empty">目前沒有內容</div>';bind()}
function renderRecent(){$("recentList").innerHTML=announcements.slice(0,5).map(cardHtml).join("")||'<div class="empty">目前沒有內容</div>';bind()}
function cardHtml(a){return `<article class="admin-card"><div><div class="admin-card-title">${a.pinned?"📌 ":""}${a.published===false?"【草稿】":"【發布】"}【${esc(a.category)}】${esc(a.title)}</div><div class="admin-card-meta">${esc(a.date)}｜圖片 ${(a.images||[]).length}｜附件 ${(a.files||[]).length}</div></div><div class="admin-actions"><button class="ghost-btn" data-edit="${a.id}">修改</button><button class="ghost-btn" data-delete="${a.id}">刪除</button></div></article>`}
function bind(){document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editPost(b.dataset.edit));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=async()=>{if(confirm("確定刪除這筆內容？"))await deleteDoc(doc(db,"announcements",b.dataset.delete))})}
function renderLibrary(){const files=announcements.flatMap(a=>(a.files||[]).map(f=>({...f,postTitle:a.title,date:a.date})));$("libraryList").innerHTML=files.length?files.map(f=>`<a class="field" href="${f.url}" target="_blank">📎 ${esc(f.name)}<br><small>來源：${esc(f.postTitle)}</small></a>`).join("<br>"):'<div class="empty">目前沒有附件</div>'}
function editPost(id){const a=announcements.find(x=>x.id===id);if(!a)return;showView("posts");$("editId").value=id;$("formTitle").textContent="修改內容";$("title").value=a.title||"";$("content").value=a.content||"";$("date").value=a.date||"";$("category").value=a.category||"公告";$("published").checked=a.published!==false;$("pinned").checked=!!a.pinned;$("images").value=(a.images||[]).map(x=>x.url).join("\n");$("files").value=(a.files||[]).map(x=>`${x.name}|${x.url}`).join("\n");scrollTo({top:0,behavior:"smooth"})}
function resetForm(){$("editId").value="";$("formTitle").textContent="新增內容";$("title").value="";$("content").value="";$("category").value="公告";$("published").checked=true;$("pinned").checked=false;$("date").valueAsDate=new Date();$("images").value="";$("files").value=""}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
